## Bag of Works
#### 1. ConutVectorizer

In [1]:
text = 'My wife likes to watch baseball games and my daughter likes to watch baseball games too.'

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cvect = CountVectorizer()
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [3]:
output = cvect.fit_transform([text])
output.toarray()

array([[1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1]], dtype=int64)

In [4]:
cvect.vocabulary_

{'my': 6,
 'wife': 10,
 'likes': 5,
 'to': 7,
 'watch': 9,
 'baseball': 2,
 'games': 4,
 'and': 0,
 'daughter': 3,
 'basdball': 1,
 'too': 8}

- 불용어(Stopwords)처리

In [5]:
# 직접 지정 
my_stopwords = ['my', 'to', 'and']
cvect = CountVectorizer(stop_words=my_stopwords)
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[1 1 1 2 2 1 2 1]]
{'wife': 7, 'likes': 4, 'watch': 6, 'baseball': 1, 'games': 3, 'daughter': 2, 'basdball': 0, 'too': 5}


In [6]:
# NLTK 에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw = stopwords.words('english')
cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[1 1 1 2 2 2 1]]
{'wife': 6, 'likes': 4, 'watch': 5, 'baseball': 1, 'games': 3, 'daughter': 2, 'basdball': 0}


In [7]:
# Scikit-Lestn에서 제공하는 불용어 사용
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[1 1 1 2 2 2 1]]
{'wife': 6, 'likes': 4, 'watch': 5, 'baseball': 1, 'games': 3, 'daughter': 2, 'basdball': 0}


- 인덱스에 해당하는 단어를 알려주는 함수

In [8]:
voca =cvect.vocabulary_
for key, value in voca.items():
    print(key,value)

wife 6
likes 4
watch 5
baseball 1
games 3
daughter 2
basdball 0


In [9]:
def get_word(index, voca):
    for key, value in voca.items():
        if index == value:
            return key
get_word(4, cvect.vocabulary_)

'likes'